#!/bin/sh

# Set these paths appropriately

BIN=/home/teegreg/Téléchargements/tree-tagger-linux-3.2.1/bin
CMD=/home/teegreg/Téléchargements/tree-tagger-linux-3.2.1/cmd
LIB=/home/teegreg/Téléchargements/tree-tagger-linux-3.2.1/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
