#!/bin/sh

# Set these paths appropriately

BIN=/home/teegreg/Téléchargements/tree-tagger-linux-3.2.1/bin
CMD=/home/teegreg/Téléchargements/tree-tagger-linux-3.2.1/cmd
LIB=/home/teegreg/Téléchargements/tree-tagger-linux-3.2.1/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
