#!/bin/sh

# Set these paths appropriately

BIN=/home/teegreg/Téléchargements/tree-tagger-linux-3.2.1/bin
CMD=/home/teegreg/Téléchargements/tree-tagger-linux-3.2.1/cmd
LIB=/home/teegreg/Téléchargements/tree-tagger-linux-3.2.1/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/french-abbreviations-utf8
PARFILE=${LIB}/french-utf8.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
